Repository NVIDIA-Merlin/models, pull requests merged in 2022-11, with the labels that each got.

#837 add tox file
  ci/test_unit.sh
  tox.ini
Labels: chore

#809 Incremental training with layer freezing exp
  examples/usecases/incremental-training-with-layer-freezing.ipynb
  tests/unit/tf/examples/test_usecase_incremental_training_layer_freezing.py
Labels: examples

#680 Add a protocol for expected interface of a model and save input schema to metadata directory
  merlin/models/api.py
  merlin/models/io.py
  merlin/models/tf/models/base.py
  merlin/models/xgb/__init__.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#786 [WIP] add an example notebook explaining hyperparameter optimization using Optuna and showing retrieval on h&m data
  .pre-commit-config.yaml
  examples/usecases/retrieval-with-hyperparameter-optimization.ipynb
  merlin/datasets/ecommerce/transactions/__init__.py
  merlin/datasets/ecommerce/transactions/schema.pbtxt
  merlin/datasets/synthetic.py
  requirements/dev.txt
  tests/unit/tf/examples/test_usecase_retrieval_with_hpo.py
Labels: documentation, examples

#843 Adding a first property to ParallelBlock
  merlin/models/tf/core/combinators.py
Labels: area/tensorflow, chore, area/session-based

#846 Fixing one_hot flag in ToTarget
  merlin/models/tf/transforms/features.py
  tests/unit/tf/transformers/test_block.py
Labels: bug

#842 Adding ProcessList to process list-columns
  merlin/models/tf/__init__.py
  merlin/models/tf/core/aggregation.py
  merlin/models/tf/core/tabular.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/tensor.py
  tests/unit/datasets/test_synthetic.py
  tests/unit/tf/blocks/retrieval/test_two_tower.py
  tests/unit/tf/blocks/test_dlrm.py
  tests/unit/tf/blocks/test_interactions.py
  tests/unit/tf/inputs/test_continuous.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/transforms/test_sequence.py
Labels: enhancement

#851 Update `ParallelBlock.select_by_tag` to handle base case and kwargs
  merlin/models/tf/core/combinators.py
  tests/unit/tf/core/test_combinators.py
Labels: enhancement

#841 Add test for Two Tower Model with Shared Embeddings
  tests/unit/tf/models/test_retrieval.py
Labels: area/tests, chore

#854 Pass params through to tox so that we can run for specified tests
  ci/test_unit.sh
  tox.ini
Labels: ci

#856 Made minor fixes in the notebooks.
  examples/03-Exploring-different-models.ipynb
  examples/05-Retrieval-Model.ipynb
Labels: examples

#860 Fixing, adding tests and docstrings to Residual Networks (DenseResidualBlock and DenseMaybeLowRank)
  merlin/models/tf/blocks/mlp.py
  merlin/models/tf/core/base.py
  tests/unit/tf/blocks/test_mlp.py
Labels: enhancement

#829 Dataset/booking
  merlin/datasets/ecommerce/__init__.py
  merlin/datasets/ecommerce/booking/__init__.py
  merlin/datasets/ecommerce/booking/dataset.py
  merlin/datasets/ecommerce/booking/transformed/__init__.py
  merlin/datasets/ecommerce/booking/transformed/schema.pbtxt
  merlin/datasets/synthetic.py
  requirements/dev.txt
  tests/unit/datasets/test_ecommerce.py
Labels: enhancement, area/data-loading, area/session-based

#859 Replaces GPT2Block by BertBlock in the masked language modeling tests
  tests/unit/tf/transformers/test_block.py
Labels: enhancement, area/session-based

#862 Adding per-batch loss metric (loss_batch)
  merlin/models/tf/models/base.py
  tests/integration/tf/test_ci_01_getting_started.py
  tests/integration/tf/test_ci_02_dataschema.py
  tests/integration/tf/test_ci_03_exploring_different_models.py
  tests/integration/tf/test_ci_06_advanced_own_architecture.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/examples/test_01_getting_started.py
  tests/unit/tf/examples/test_02_dataschema.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/examples/test_06_advanced_own_architecture.py
  tests/unit/tf/examples/test_usecase_accelerate_training_by_lazyadam.py
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
  tests/unit/tf/examples/test_usecase_incremental_training_layer_freezing.py
  tests/unit/tf/examples/test_usecase_pretrained_embeddings.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_base.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/outputs/test_regression.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
Labels: enhancement

#868 Fix passing targets to `logits_scaler`
  merlin/models/tf/outputs/base.py
  tests/unit/tf/models/test_base.py
Labels: bug

#864 docs: Add basic SEO configuration
  docs/source/conf.py
Labels: documentation

#877 remove coverage parameters from pytest call
  ci/test_unit.sh
Labels: ci, chore

#872 Pin fiddle to 0.2.2 so that tests run with pip install
  requirements/dev.txt
Labels: ci

#874 Make path optional in get_booking
  merlin/datasets/ecommerce/booking/dataset.py
Labels: bug

#833 Add test for retrieval model with transformer block
  merlin/models/tf/models/base.py
  tests/unit/tf/transformers/test_block.py
Labels: area/tests, chore

#884 Update docs building actions
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
Labels: chore, skip-changelog

#888 Do not copy source to docs output
  .github/workflows/docs-remove-stale-reviews.yaml
  docs/source/conf.py
Labels: documentation

#853 T4rec use case
  examples/usecases/transformers-next-item-prediction.ipynb
  merlin/datasets/ecommerce/booking/raw/__init__.py
  merlin/datasets/ecommerce/booking/raw/schema.pbtxt
  merlin/datasets/synthetic.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: examples

#895 Remove tensorflow dependencies from `requirements/dev.txt`
  requirements/dev.txt
Labels: ci

#897 Skip retrieval_with_hpo notebook test when optuna is not installed
  tests/unit/tf/examples/test_usecase_retrieval_with_hpo.py
Labels: ci, chore

#855 Adding Multi-GPU Data Parallel Example
  examples/usecases/multi-gpu-data-parallel-training.ipynb
  tests/unit/tf/examples/test_usecase_data_parallel.py
Labels: examples

#892 Preventing silent error when evaluating V1 retrieval models (TwoTower, MF)
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_retrieval.py
Labels: bug

#880 Making InputBlockV2(..., embeddings) deprecated and adjusting tests to use categorical arg
  merlin/models/tf/inputs/base.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/transformers/test_block.py
Labels: bug

#899 Add skip if transformers not available for next item prediction notebook test
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: ci

#849 Session-based example using dressipi dataset and XLNet architecture
  examples/images/XLNet_ecommerce.png
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
Labels: examples, area/session-based

#901 update drafter to work on tags only and update cpu ci to target branch
  .github/workflows/datasets.yml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pytorch.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
Labels: documentation, ci, chore

#865 docs: Add calver to semver banner
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#903 Add Reference to Transformer4Rec for PyTorch support
  README.md
Labels: documentation

#900 Update retrieval notebook to new api
  examples/05-Retrieval-Model.ipynb
Labels: examples
