Repository NVIDIA-Merlin/models, pull requests merged in 2022-03, with the labels that each got.

#189 Create the necessary blocks/methods for ItemRetrieval evaluation
  merlin/models/data/music_streaming/schema.json
  merlin/models/data/synthetic.py
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/__init__.py
  merlin/models/tf/blocks/core/aggregation.py
  merlin/models/tf/blocks/core/index.py
  merlin/models/tf/blocks/core/inputs.py
  merlin/models/tf/blocks/core/masking.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/experts.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/blocks/outer_product.py
  merlin/models/tf/blocks/retrieval/__init__.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/blocks/retrieval/matrix_factorization.py
  merlin/models/tf/blocks/retrieval/top_k.py
  merlin/models/tf/blocks/retrieval/two_tower.py
  merlin/models/tf/blocks/sampling/__init__.py
  merlin/models/tf/blocks/sampling/base.py
  merlin/models/tf/blocks/sampling/cross_batch.py
  merlin/models/tf/blocks/sampling/in_batch.py
  merlin/models/tf/blocks/sampling/queue.py
  merlin/models/tf/core.py
  merlin/models/tf/features/embedding.py
  merlin/models/tf/losses/__init__.py
  merlin/models/tf/losses/base.py
  merlin/models/tf/losses/listwise.py
  merlin/models/tf/losses/pairwise.py
  merlin/models/tf/metrics/ranking.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/models/utils.py
  merlin/models/tf/prediction/item_prediction.py
  merlin/models/tf/prediction_tasks/__init__.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/multi.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/regression.py
  merlin/models/tf/prediction_tasks/retrieval.py
  merlin/models/tf/utils/batch_utils.py
  merlin/models/tf/utils/testing_utils.py
  merlin/models/tf/utils/tf_utils.py
  tests/tf/blocks/core/__init__.py
  tests/tf/blocks/core/test_aggregation.py
  tests/tf/blocks/core/test_base.py
  tests/tf/blocks/core/test_index.py
  tests/tf/blocks/core/test_masking.py
  tests/tf/blocks/core/test_transformations.py
  tests/tf/blocks/retrieval/__init__.py
  tests/tf/blocks/retrieval/test_matrix_factorization.py
  tests/tf/blocks/retrieval/test_two_tower.py
  tests/tf/prediction/test_next_item.py
  tests/tf/utils/test_batch.py
Labels: area/tensorflow, size/XXL, status/needs-review

#229 chore: add PR doc previews
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/tensorflow.yml
  .pre-commit-config.yaml
Labels: documentation, status/needs-review

#251 chore: Trigger on closed pull requests
  .github/workflows/tensorflow.yml
Labels: status/needs-review

#193 docs: Incremental improvements
  README.md
  docs/README.md
  docs/source/conf.py
  docs/source/getting_started.md
  docs/source/index.rst
  docs/source/models_overview.md
Labels: status/needs-review

#257 Set up automated docstring coverage checks
  .pre-commit-config.yaml
  requirements/dev.txt
Labels: documentation

#238 Automatic setting of retrieval model top-k evaluation
  merlin/models/data/music_streaming/data.parquet
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/index.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/utils/batch_utils.py
  merlin/models/tf/utils/mixins.py
  merlin/models/tf/utils/tf_utils.py
  tests/tf/models/test_retrieval.py
  tests/tf/prediction/test_next_item.py
  tests/tf/utils/test_batch.py
Labels: area/tensorflow, status/needs-review, area/retrieval

#264 Fixing MLPBlock saving with regularizers
  merlin/models/tf/blocks/core/combinators.py
  tests/tf/blocks/test_mlp.py
Labels: bug, area/tensorflow, status/needs-review

#275 Fix bug in tower saving where all features were required
  merlin/models/tf/blocks/retrieval/base.py
  tests/tf/blocks/retrieval/test_two_tower.py
Labels: area/tensorflow, size/XS, status/needs-review, area/retrieval

#276 Move interrogate docstring coverage settings to pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: documentation

#280 Fix MatrixFactorizationModel bug
  merlin/models/tf/blocks/core/base.py
  tests/tf/models/test_ranking.py
Labels: status/needs-review

#271 Implementation of DeepFM model
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/models/ranking.py
  tests/tf/blocks/core/test_transformations.py
  tests/tf/blocks/test_interactions.py
  tests/tf/models/test_ranking.py
Labels: area/tensorflow, status/needs-review, area/ranking

#279 Item retrieval evaluation fixes
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/index.py
  merlin/models/tf/models/base.py
Labels: status/needs-review

#286 [Doc] a hyperlink missing
  README.md
Labels: area/documentation

#212 docs: Add API documentation
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/tensorflow.yml
  .gitignore
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  requirements/dev.txt
Labels: documentation, status/needs-review

#293 Exclude additional directories from docstring coverage req't
  pyproject.toml
Labels: documentation, area/documentation

#294 fix evaluation loss equal to zero and add docstrings
  merlin/models/tf/prediction_tasks/base.py
Labels: status/needs-review

#299 fix: Do not rebuild on PR close
  .github/workflows/tensorflow.yml
Labels: status/needs-review

#262 Retrieval models (ALI-CCP)- Two-Tower model example
  examples/01-Getting-started.ipynb
  examples/02-Merlin-Models-and-NVTabular-applying-to-your-own-dataset.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Retrieval-Model.ipynb
  examples/images/TwoTower.png
  merlin/models/utils/example_utils.py
Labels: status/needs-review

#300 Exporting ranking models
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
Labels: area/examples

#295 first draft of advanced example notebook
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/images/residual_interaction.png
  merlin/models/tf/__init__.py
  merlin/models/tf/dataset.py
Labels: area/examples, status/needs-review
