Repository NVIDIA-Merlin/models, pull requests merged in 2022-07, with the labels that each got.

#541 Add new block EmbeddingTable
  merlin/models/tf/__init__.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement

#549 Enable serialization of TensorInitializer
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/utils/test_tf_utils.py
Labels: bug

#539 Adding schema's to manifest
  MANIFEST.in
Labels: status/needs-review, chore

#518 Breaking out BaseModel to support sub-classing
  merlin/models/tf/__init__.py
  merlin/models/tf/models/base.py
  tests/unit/tf/blocks/core/test_masking.py
  tests/unit/tf/models/test_base.py
Labels: enhancement, status/needs-review

#551 Make blocks part of Model and not of SequentialBlock
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/batch_utils.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/blocks/core/test_base.py
  tests/unit/tf/blocks/core/test_transformations.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/utils/test_batch.py
Labels: status/needs-review, chore

#555 Replace usage of tensorflow.python.keras with tensorflow.keras
  .pre-commit-config.yaml
  ci/lint_tensorflow.sh
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/aggregation.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/sampling/queue.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/metrics/evaluation.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/retrieval.py
Labels: chore

#558 Removing Queue-based negative-sampling for now
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/sampling/cross_batch.py
  tests/unit/tf/prediction_tasks/test_next_item.py
  tests/unit/tf/prediction_tasks/test_sampling.py
Labels: breaking

#556 Adding AsRaggedTensors transformation
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/utils/tf_utils.py
Labels: enhancement

#552 Add Cond Layer to tensorflow combinators
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/blocks/core/test_combinators.py
Labels: enhancement

#557 Remove masking for now
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/masking.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/dataset.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/prediction_tasks/next_item.py
  tests/unit/tf/blocks/core/test_masking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_next_item.py
Labels: breaking

#560 Add In-Batch Negative Sampling Block for positive-only batches
  merlin/models/tf/data_augmentation/__init__.py
  merlin/models/tf/data_augmentation/negative_sampling.py
  merlin/models/tf/dataset.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/_conftest.py
  tests/unit/tf/data_augmentation/__init__.py
  tests/unit/tf/data_augmentation/negative_sampling.py
Labels: enhancement

#554 Allow for blocks in the Model to transform the targets
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/blocks/core/context.py
  merlin/models/tf/blocks/core/prediction.py
  merlin/models/tf/blocks/mlp.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/data_augmentation/negative_sampling.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/utils/tf_utils.py
  merlin/models/utils/misc_utils.py
  tests/unit/tf/blocks/core/test_base.py
  tests/unit/tf/blocks/core/test_prediction.py
  tests/unit/tf/data_augmentation/test_negative_sampling.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/prediction_tasks/test_next_item.py
Labels: enhancement

#565 Moving tf/core/blocks to tf/core
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/cross.py
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/blocks/experts.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/blocks/mlp.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/blocks/retrieval/matrix_factorization.py
  merlin/models/tf/blocks/retrieval/two_tower.py
  merlin/models/tf/blocks/sampling/base.py
  merlin/models/tf/core/__init__.py
  merlin/models/tf/core/aggregation.py
  merlin/models/tf/core/base.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/index.py
  merlin/models/tf/core/prediction.py
  merlin/models/tf/core/tabular.py
  merlin/models/tf/core/transformations.py
  merlin/models/tf/data_augmentation/negative_sampling.py
  merlin/models/tf/dataset.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/benchmark.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/retrieval.py
  merlin/models/tf/utils/batch_utils.py
  tests/unit/tf/blocks/retrieval/test_matrix_factorization.py
  tests/unit/tf/blocks/retrieval/test_two_tower.py
  tests/unit/tf/core/__init__.py
  tests/unit/tf/core/test_aggregation.py
  tests/unit/tf/core/test_base.py
  tests/unit/tf/core/test_combinators.py
  tests/unit/tf/core/test_index.py
  tests/unit/tf/core/test_prediction.py
  tests/unit/tf/core/test_tabular.py
  tests/unit/tf/core/test_transformations.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_next_item.py
Labels: chore

#568 Attribute source of MF image
  docs/source/models_overview.md
Labels: documentation

#567 Support training with UniformNegativeSampling
  merlin/models/tf/data_augmentation/negative_sampling.py
  tests/unit/tf/data_augmentation/test_negative_sampling.py
Labels: enhancement, skip-changelog

#582 Fixing bug in saving of two-tower model in TF<2.9
  merlin/models/tf/models/base.py
Labels: bug, skip-changelog

#583 Update UniformNegativeSampling to handle targets and add optional control for testing
  merlin/models/tf/data_augmentation/negative_sampling.py
  tests/unit/tf/data_augmentation/test_negative_sampling.py
Labels: enhancement

#586 Attempt to remove docs dependencies
  docs/source/conf.py
  requirements/dev.txt
Labels: chore

#572 Keep Dataloader lazy when using map operations
  merlin/models/loader/backend.py
  tests/unit/tf/test_dataset.py
Labels: bug

#584 Add Keras layer_test function to testing_utils
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/core/test_combinators.py
Labels: ci

#588 Add signature checks for various models like two-tower & DLRM
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
Labels: bug

#587 Hashed cross
  merlin/models/tf/__init__.py
  merlin/models/tf/core/transformations.py
  tests/unit/tf/core/test_transformations.py
Labels: enhancement, status/needs-review

#595 Trying to make model unit-tests faster
  .github/workflows/datasets.yml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
  merlin/models/tf/dataset.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_benchmark.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/utils/test_batch.py
Labels: chore

#592 Add EmbeddingOptions arg in the DLRM block
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/models/ranking.py
Labels: enhancement, area/ranking

#597 Fix CategoricalOneHot with compute_output_shape and check inputs.
  merlin/models/tf/core/transformations.py
  tests/unit/tf/core/test_transformations.py
Labels: enhancement, status/needs-review

#603 Stop reordering columns in merlin.models.xgb.dataset_to_xy
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: bug

#581 Add multi optimizer
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/multi_optimizers.py
  tests/unit/tf/blocks/test_multi_optimizers.py
Labels: enhancement

#610 Use labels instead of predictions in XGBoost eval data
  merlin/models/xgb/__init__.py
Labels: bug

#589 Introducing new base-implementations to replace prediction-tasks
  merlin/models/tf/__init__.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/prediction.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/predictions/__init__.py
  merlin/models/tf/predictions/base.py
  merlin/models/tf/predictions/classification.py
  merlin/models/tf/predictions/regression.py
  tests/unit/tf/predictions/__init__.py
  tests/unit/tf/predictions/test_base.py
  tests/unit/tf/predictions/test_classification.py
  tests/unit/tf/predictions/test_regression.py
Labels: enhancement
