Repository NVIDIA-Merlin/models, pull requests merged in 2022-10, with the labels that each got.

#767 Skip running test for traditional ML notebook unless GPU available
  tests/unit/tf/examples/test_07_train_traditional_models.py
Labels: ci

#745 Transformations of sequence inputs for sequential/session-based recommendation
  merlin/models/tf/__init__.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/transforms/test_sequence.py
Labels: enhancement, status/needs-review, area/session-based

#779 Add test for `unique_rows_by_features` and update to propagate schema correctly
  merlin/models/utils/dataset.py
  tests/unit/tf/utils/test_dataset.py
Labels: enhancement

#771 Transformer Block (for HuggingFace support)
  merlin/models/tf/__init__.py
  merlin/models/tf/transformers/__init__.py
  merlin/models/tf/transformers/block.py
  merlin/models/tf/transformers/transforms.py
  merlin/models/utils/dependencies.py
  requirements/dev.txt
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transformers/test_transforms.py
Labels: enhancement, area/tensorflow, area/session-based

#784 Fix default variant in the get_movielens() func
  merlin/datasets/entertainment/movielens/dataset.py
Labels: examples

#782 Introduce TopKEncoder for retrieval
  merlin/models/tf/__init__.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/core/prediction.py
  merlin/models/tf/outputs/topk.py
  merlin/models/tf/utils/batch_utils.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/outputs/test_topk.py
Labels: enhancement, area/tensorflow, status/needs-review, area/retrieval

#761 Introducing RetrievalModelV2 to unify two-tower & session-based enhancement
  merlin/models/tf/__init__.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/core/index.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/outputs/contrastive.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/models/test_base.py
Labels: enhancement, area/tensorflow, area/retrieval, area/session-based

#792 Adding pre to model.fit, model.evaluate & model.predict
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#787 Support Compiling Model More than Once
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#780 Introduces Masked Language Modeling for Transformers
  merlin/models/tf/__init__.py
  merlin/models/tf/losses/pairwise.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/transforms/tensor.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_sequence.py
Labels: enhancement, area/session-based

#794 Change output format of ToTarget to tuple
  merlin/models/tf/transforms/features.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/transforms/test_features.py
Labels: bug

#781 Update requirements/tensorflow.txt
  requirements/tensorflow.txt
Labels: chore

#800 Fix the rank of predictions returned by ContrastiveOutout
  merlin/models/tf/losses/pairwise.py
  merlin/models/tf/outputs/contrastive.py
  tests/unit/tf/outputs/test_contrastive.py
Labels: bug, area/retrieval, P0

#797 Add `python_requires` specifying 3.8 as minimum Python version
  setup.py
Labels: chore

#795 Use pytest-xdist with tensorflow tests to reduce running time of tests
  Makefile
  requirements/dev.txt
Labels: chore

#812 Add L2-batch regularization to EmbeddingTable
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement, area/api, status/needs-review, P1

#811 Add LogQ correction support to the new ModelOutput API
  merlin/models/tf/core/prediction.py
  merlin/models/tf/outputs/contrastive.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/transforms/bias.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/transforms/test_bias.py
Labels: bug, area/api, size/S, status/needs-review, P0

#813 [wip] Add tox.ini and update paths in example notebooks
  examples/02-Merlin-Models-and-NVTabular-integration.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  merlin/models/utils/example_utils.py
  tests/unit/datasets/test_ecommerce.py
  tests/unit/tf/examples/test_02_dataschema.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/examples/test_04_export_ranking_models.py
  tests/unit/tf/examples/test_05_export_retrieval_model.py
  tests/unit/tf/examples/test_06_advanced_own_architecture.py
Labels: ci, chore

#816 fix OOM issue in accelerate-training-of-large-embedding-tables-by-LazyAdam nb unit test
  examples/usecases/accelerate-training-of-large-embedding-tables-by-LazyAdam.ipynb
  tests/unit/torch/features/test_embedding.py
Labels: enhancement, chore

#815 Add support for LogitsTemperatureScaler in the new ModelOutput API
  merlin/models/tf/core/prediction.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/transforms/bias.py
  tests/unit/tf/outputs/test_base.py
Labels: bug, status/needs-review, area/retrieval, P0

#817 Fix `EmbeddingFeatures` serialization/deserialization when a feature is named 'name'
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: bug

#826 [Test] - fix pretrained embedding unittest
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  tests/unit/tf/examples/test_usecase_pretrained_embeddings.py
Labels: enhancement

#828 Adding SequenceSummary transforms for transformers
  merlin/models/tf/transformers/transforms.py
  tests/unit/tf/transformers/test_transforms.py
Labels: enhancement, area/session-based

#830 Ensure metrics passed to `model.compile()` are always reset
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_base.py
Labels: bug

#839 Trying to add Bokeh to dev-requirements to fix failing xgb-tests
  requirements/dev.txt
Labels: bug

#832 Quick fix to parse post in transformer when a string is passed in
  merlin/models/tf/transformers/block.py
  tests/unit/tf/transformers/test_block.py
Labels: bug, area/session-based

#827 Add `seed` to `TopKMetric` for consistent metrics when ties in ranking
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/transformers/test_block.py
Labels: enhancement

#838 Removing mask from PredictionContext, since it's unused
  merlin/models/tf/core/prediction.py
Labels: enhancement, size/XS

#790 Retrieval models definition using new RetrievalModelV2, InputBlockV2 and ModelOutput classes
  merlin/models/tf/__init__.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/core/prediction.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/outputs/topk.py
  tests/common/tf/retrieval/retrieval_config.py
  tests/common/tf/retrieval/retrieval_tests_common.py
  tests/common/tf/retrieval/retrieval_utils.py
  tests/integration/tf/retrieval/test_integration_retrieval.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/models/test_retrieval.py
Labels: enhancement, area/tensorflow, size/L, area/retrieval
