Repository NVIDIA-Merlin/models, pull requests merged in 2022-08, with the labels that each got.

#600 Supports task-specific sample weights, weighed_metrics and fixes InputBlockV2
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/core/base.py
  merlin/models/tf/core/prediction.py
  merlin/models/tf/core/transformations.py
  merlin/models/tf/data_augmentation/negative_sampling.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/multi.py
  tests/unit/tf/core/test_index.py
  tests/unit/tf/data_augmentation/test_negative_sampling.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/inputs/test_tabular.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
Labels: enhancement, area/ranking, area/research

#590 Hashed Crosses for all levels
  merlin/models/tf/__init__.py
  merlin/models/tf/core/transformations.py
  tests/unit/tf/core/test_transformations.py
Labels: enhancement

#612 Enable predict in XGBoost without targets in provided dataset
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: bug

#616 Fix lightfm evaluate code
  merlin/models/lightfm/__init__.py
  tests/unit/lightfm/test_lightfm.py
Labels: bug

#594 Tf/contrastive prediction
  merlin/models/tf/__init__.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/predictions/base.py
  merlin/models/tf/predictions/dot_product.py
  merlin/models/tf/predictions/sampling/__init__.py
  merlin/models/tf/predictions/sampling/base.py
  merlin/models/tf/predictions/sampling/in_batch.py
  tests/unit/tf/predictions/test_dot_product.py
  tests/unit/tf/predictions/test_sampling.py
Labels: enhancement, status/needs-review

#602 Add LazyAdam optimizer
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/multi_optimizers.py
  merlin/models/tf/blocks/optimizer.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/blocks/test_multi_optimizers.py
  tests/unit/tf/blocks/test_optimizer.py
  tests/unit/tf/core/test_combinators.py
Labels: enhancement, status/needs-review

#631 Enable `TabularData` to be used with `EmbeddingTable`
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement, area/tensorflow

#632 Enable static weights to be used with `EmbeddingTable.from_pretrained`
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement, area/tensorflow

#623 Add Wide Deep model
  merlin/models/tf/__init__.py
  merlin/models/tf/core/transformations.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/models/benchmark.py
  merlin/models/tf/models/ranking.py
  tests/unit/tf/core/test_transformations.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement, status/needs-review

#637 Update stacking in `DLRMBlock` to use correct axis for the dot product.
  merlin/models/tf/blocks/dlrm.py
  tests/unit/tf/blocks/test_dlrm.py
Labels: bug

#645 Remove `-e` from pip install commands in github workflows
  .github/workflows/datasets.yml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
Labels: ci, chore

#646 Update `versioneer` from 0.20 to 0.23
  merlin/models/__init__.py
  merlin/models/_version.py
  versioneer.py
Labels: chore

#634 Add `trainable` and `embeddings_initializers` args to `Embeddings` function
  merlin/models/tf/inputs/embedding.py
Labels: enhancement, area/api

#615 Enable saving of TwoTowerModel
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/blocks/sampling/cross_batch.py
  merlin/models/tf/blocks/sampling/in_batch.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/prediction_tasks/retrieval.py
  tests/unit/tf/blocks/retrieval/test_base.py
  tests/unit/tf/blocks/sampling/__init__.py
  tests/unit/tf/blocks/sampling/test_cross_batch.py
  tests/unit/tf/blocks/sampling/test_in_batch.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_retrieval.py
Labels: bug

#648 Add unit test for the trainable embeddings func
  tests/unit/tf/inputs/test_embedding.py
Labels: area/tests, chore

#619 Enable customization of embeddings in DLRM Model
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/models/ranking.py
  tests/unit/tf/blocks/test_dlrm.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement, area/api

#633 Tf/categorical prediction v2
  merlin/models/tf/__init__.py
  merlin/models/tf/models/base.py
  merlin/models/tf/predictions/base.py
  merlin/models/tf/predictions/classification.py
  merlin/models/tf/predictions/dot_product.py
  merlin/models/tf/predictions/regression.py
  merlin/models/tf/predictions/sampling/base.py
  merlin/models/tf/predictions/sampling/popularity.py
  tests/unit/tf/predictions/test_base.py
  tests/unit/tf/predictions/test_classification.py
  tests/unit/tf/predictions/test_regression.py
  tests/unit/tf/predictions/test_sampling.py
Labels: enhancement, area/api, size/M, status/needs-review

#654 enhance pretrained-embeddings example to set trainable=False for the pre-trained embeddings
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
Labels: enhancement, area/examples

#653 Breaks ties of top-k metrics
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/utils/test_tf_utils.py
Labels: bug

#657 Removing use of synthetic data in traditional models notebook test.
  tests/unit/tf/examples/test_07_train_traditional_models.py
Labels: ci, chore, skip-changelog

#649 Restructuring Embeddings
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/utils/schema_utils.py
  tests/unit/tf/blocks/test_dlrm.py
  tests/unit/tf/blocks/test_optimizer.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/inputs/test_tabular.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement

#656 Add `save` and `load` methods to XGBoost class
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement

#635 Add Layer freezing
  merlin/models/tf/core/combinators.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#661 add tracking logo to examples/07
  examples/07-Train-traditional-ML-models-using-the-Merlin-Models-API.ipynb
Labels: documentation, examples

#614 Add CategoryEncoding transformation block
  merlin/models/tf/__init__.py
  merlin/models/tf/core/transformations.py
  merlin/models/tf/models/ranking.py
  tests/unit/tf/core/test_transformations.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement, status/needs-review

#662 Add `dtype` conversion for continuous columns in synthetic data generation
  merlin/datasets/synthetic.py
  tests/unit/datasets/test_synthetic.py
Labels: bug, chore

#690 Fix ecommerce session based test
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
Labels: bug, ci, chore

#638 Improvements in Wide and Deep architecture and example test based on the paper
  merlin/models/tf/core/aggregation.py
  merlin/models/tf/core/transformations.py
  merlin/models/tf/models/ranking.py
  tests/unit/tf/core/test_transformations.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement

#693 update logo usecase
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
Labels: examples

#686 Filter features in ParallelBlock
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/losses/pairwise.py
  merlin/models/tf/models/base.py
Labels: enhancement, area/tensorflow
