Repository NVIDIA-Merlin/models, pull requests merged in 2022-09, with the labels that each got.

#700 Extend `EmbeddingTable` and `Embeddings` with support for shared embeddings
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement

#708 Separate the `dev` and `docs` requirements
  .github/workflows/tensorflow.yml
  requirements/dev.txt
  requirements/docs.txt
  setup.py
Labels: ci, chore

#705 Add EncoderBlock
  .github/workflows/tensorflow.yml
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/core/base.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/base.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
Labels: enhancement

#723 Fix Feature Engineering Dressipi
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
Labels: examples

#741 Fixes RegressionTask which was raising an error because compute_output_shape() was not defined
  merlin/models/tf/prediction_tasks/regression.py
  tests/unit/tf/prediction_tasks/test_regression.py
Labels: bug

#710 Move transformation-layers to sub package
  examples/01-Getting-started.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/blocks/retrieval/matrix_factorization.py
  merlin/models/tf/data_augmentation/__init__.py
  merlin/models/tf/data_augmentation/misc.py
  merlin/models/tf/dataset.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/retrieval.py
  merlin/models/tf/predictions/base.py
  merlin/models/tf/transforms/__init__.py
  merlin/models/tf/transforms/bias.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/transforms/noise.py
  merlin/models/tf/transforms/regularization.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/transforms/tensor.py
  tests/common/tf/retrieval/retrieval_utils.py
  tests/unit/tf/data_augmentation/__init__.py
  tests/unit/tf/data_augmentation/test_misc.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/predictions/test_base.py
  tests/unit/tf/predictions/test_classification.py
  tests/unit/tf/transforms/__init__.py
  tests/unit/tf/transforms/test_bias.py
  tests/unit/tf/transforms/test_features.py
  tests/unit/tf/transforms/test_negative_sampling.py
  tests/unit/tf/transforms/test_noise.py
  tests/unit/tf/transforms/test_tensor.py
Labels: enhancement, breaking

#724 Implement `on_epoch_end` method on `BatchedDataset`
  merlin/models/tf/dataset.py
  tests/unit/tf/models/test_base.py
Labels: bug

#715 Introducing Outputs-V2
  merlin/models/tf/__init__.py
  merlin/models/tf/models/base.py
  merlin/models/tf/outputs/__init__.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/outputs/contrastive.py
  merlin/models/tf/outputs/regression.py
  merlin/models/tf/outputs/sampling/__init__.py
  merlin/models/tf/outputs/sampling/base.py
  merlin/models/tf/outputs/sampling/in_batch.py
  merlin/models/tf/outputs/sampling/popularity.py
  merlin/models/tf/predictions/dot_product.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/outputs/__init__.py
  tests/unit/tf/outputs/test_base.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/outputs/test_regression.py
  tests/unit/tf/outputs/test_sampling.py
  tests/unit/tf/predictions/test_dot_product.py
Labels: enhancement

#716 Example notebook of Wide&Deep model
  examples/03-Exploring-different-models.ipynb
  examples/images/wide_and_deep.png
  merlin/models/tf/models/ranking.py
  tests/integration/tf/test_ci_03_exploring_different_models.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/models/test_ranking.py
Labels: enhancement

#754 Making InputBlockV2 more generic
  merlin/models/tf/__init__.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  tests/unit/tf/blocks/test_optimizer.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/inputs/test_tabular.py
Labels: enhancement

#751 Fixed inconsistency on multi-task learning metrics due to a mismatch or tasks and metrics order
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
Labels: bug

#717 Added InputBlockV2 support to DeepFMModel (refactored and fixed) and DCNModel
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/blocks/test_interactions.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/transforms/test_features.py
Labels: area/api, area/ranking, chore

#756 Update `ItemRetrievalScorer` to use tf_inspect to get call args
  merlin/models/tf/blocks/retrieval/base.py
Labels: chore

#740 Add loader transforms
  examples/03-Exploring-different-models.ipynb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/utils/batch_utils.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/core/test_index.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/test_loader.py
  tests/unit/tf/transforms/test_features.py
  tests/unit/tf/transforms/test_negative_sampling.py
Labels: enhancement, breaking

#701 Add select_by_tag to ParallelBlock
  merlin/models/tf/core/base.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/tabular.py
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/core/test_combinators.py
  tests/unit/tf/core/test_tabular.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement

#757 Fix saving + reloading models with ContrastiveOutput
  merlin/models/tf/outputs/contrastive.py
  tests/unit/tf/outputs/test_contrastive.py
Labels: bug, enhancement

#758 Bug when predicting with list-column
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/models/test_ranking.py
Labels: bug

#737 Add `BroadcastToSequence` Layer to broadcast context features to match sequence shapes.
  merlin/models/tf/__init__.py
  merlin/models/tf/transforms/features.py
  tests/unit/tf/transforms/test_features.py
Labels: enhancement

#726 Update tensorflow version test matrix version specifiers for clarity
  .github/workflows/tensorflow.yml
Labels: ci

#759 Add test for `TwoTowerModel` with `InputBlockV2` and `Embeddings`
  merlin/models/tf/inputs/base.py
  tests/unit/tf/blocks/retrieval/test_two_tower.py
Labels: enhancement

#703 Return correct type from data augmentation layer depending on the context
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/transforms/test_negative_sampling.py
Labels: enhancement

#763 Remove `cluster_type` from `dask_client` test fixture
  tests/conftest.py
Labels: ci, chore

#762 Revert "XGBoost - Use DaskDMatrix for evals data to ensure metrics in logs match result of evaluate"
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: ci, skip-changelog

#766 Improve reliability of `test_train_metrics_steps` with a custom test metric
  tests/unit/tf/models/test_base.py
Labels: ci

#773 Show how to use intersphinx links for docs
  CONTRIBUTING.md
  merlin/models/tf/models/ranking.py
Labels: documentation

#747 Add multi-optimizer example nb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/usecases/accelerate-training-of-large-embedding-tables-by-LazyAdam.ipynb
  tests/unit/tf/examples/test_usecase_accelerate_training_by_lazyadam.py
Labels: enhancement, examples

#776 Add TensorFlow 2.10 to versions in test matrix
  .github/workflows/tensorflow.yml
Labels: ci

#768 Adding transformers as backend
  merlin/models/tf/transformers/__init__.py
  pyproject.toml
  requirements/transformers.txt
  setup.py
  tests/conftest.py
  tests/unit/tf/transformers/__init__.py
  tests/unit/tf/transformers/test_block.py
Labels: enhancement, area/session-based

#774 Extend ListToDense to support a single tensor as input
  merlin/models/tf/transforms/tensor.py
  tests/unit/tf/transforms/test_tensor.py
Labels: enhancement, area/tensorflow, area/session-based

#777 remove inital usecases
  examples/usecases/e-commerce.ipynb
  examples/usecases/music-streaming.ipynb
  examples/usecases/social.ipynb
Labels: examples

#760 Update ToTarget to accept Tags and all columns in Schema as targets
  merlin/models/tf/transforms/features.py
  tests/unit/tf/transforms/test_features.py
Labels: enhancement, area/tensorflow
