Repository NVIDIA-Merlin/models, pull requests merged in 2022-05, with the labels that each got.

#416 Remove `.python-version` file
  .python-version
Labels: area/packaging

#397 Update the tags selection from the schema by excluding the target variable
  merlin/models/loader/backend.py
  merlin/models/tf/blocks/core/inputs.py
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/dataset.py
  merlin/models/tf/utils/batch_utils.py
  merlin/models/torch/utils/data_utils.py
  tests/tf/test_dataset.py
Labels: area/api, area/data-loading, epic?

#404 docs: Use sphinx-ext-toc to control examples
  .gitignore
  README.md
  docs/README.md
  docs/source/additional_resources.rst
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/toc.yaml
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/README.md
  examples/README.rst
  requirements/dev.txt
Labels: area/documentation, status/needs-review

#357 Added TensorInitializer that can be used to initialize variables/embeddings with pretrained weights
  merlin/models/tf/__init__.py
  merlin/models/tf/utils/tf_utils.py
  tests/tf/features/test_embedding.py
Labels: size/S, status/needs-review, epic?

#418 Create `FeatureCollection` as a way to pass input features to blocks
  merlin/models/config/schema.py
  tests/config/test_schema.py
Labels: area/api

#417 Rename `BlockContext` to `ModelContext`
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  tests/tf/blocks/core/test_masking.py
  tests/tf/prediction_tasks/test_next_item.py
  tests/tf/test_core.py
  tests/tf/test_dataset.py
Labels: area/api

#425 Rename "mask schema" to "mask" or "feature mask"
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/masking.py
  tests/tf/blocks/core/test_masking.py
Labels: area/api

#432 Make Model creation explicit
  docs/source/models_overview.md
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  merlin/models/mypy.py
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/models/benchmark.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/utils/testing_utils.py
  setup.cfg
  tests/tf/blocks/core/test_masking.py
  tests/tf/blocks/core/test_transformations.py
  tests/tf/blocks/retrieval/test_matrix_factorization.py
  tests/tf/blocks/retrieval/test_two_tower.py
  tests/tf/blocks/test_cross.py
  tests/tf/models/test_ranking.py
  tests/tf/prediction_tasks/test_classification.py
  tests/tf/prediction_tasks/test_multi_task.py
  tests/tf/prediction_tasks/test_next_item.py
  tests/tf/prediction_tasks/test_regression.py
  tests/tf/test_core.py
  tests/tf/test_dataset.py
  tests/tf/utils/test_batch.py
Labels: area/api

#435 Add common release-drafter configuration
  .github/release-drafter.yml
  .pre-commit-config.yaml
Labels: documentation

#434 Add validation for movielens variant and fix docstring
  merlin/datasets/entertainment/movielens/dataset.py
  merlin/models/lightfm/__init__.py
  tests/datasets/test_entertainment.py
Labels: bug

#428 Create `FeatureContext` and pass it to model layers with `call_layer`
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/blocks/core/context.py
  merlin/models/tf/blocks/core/masking.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/tf_utils.py
  tests/tf/blocks/core/test_masking.py
Labels: area/api

#443 Move masking into the `FeatureContext`
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/context.py
  merlin/models/tf/blocks/core/masking.py
  merlin/models/tf/models/base.py
  tests/tf/blocks/core/test_masking.py
Labels: area/api

#398 Making EmbeddingOptions.embedding_dims to have priority over .inferred_embedding_dims
  merlin/models/tf/features/embedding.py
  tests/tf/features/test_embedding.py
Labels: status/needs-review

#447 Making YoutubeDNNRetrievalModel more configurable
  merlin/models/tf/blocks/core/inputs.py
  merlin/models/tf/models/retrieval.py
  tests/tf/models/test_retrieval.py
Labels: status/needs-review

#449 Remove the `mask` variable from the `ModelContext`
  merlin/models/tf/blocks/core/masking.py
Labels: area/api

#440 Make use of model_test for all ranking- and benchmark-models
  merlin/models/tf/blocks/core/aggregation.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/blocks/test_cross.py
  tests/unit/tf/features/test_continuous.py
  tests/unit/tf/features/test_embedding.py
  tests/unit/tf/features/test_tabular.py
  tests/unit/tf/models/test_benchmark.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/prediction_tasks/test_classification.py
  tests/unit/tf/prediction_tasks/test_regression.py
Labels: size/S, status/needs-review

#452 Fixing the inconsistency when exporting embeddings to cudf DataFrame
  merlin/models/tf/features/embedding.py
  tests/unit/tf/features/test_embedding.py
Labels: status/needs-review

#453 Add labels to PRs for change log
  CONTRIBUTING.md
Labels: chore

#455 Getting rid of feature-variables in ModelContext
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/blocks/sampling/cross_batch.py
  merlin/models/tf/blocks/sampling/queue.py
  tests/unit/tf/blocks/core/test_base.py
  tests/unit/tf/prediction_tasks/test_next_item.py
  tests/unit/tf/test_core.py
Labels: enhancement

#456 Parametrize base-model-tests to run in both graph- and eager-mode
  tests/unit/tf/models/test_base.py
Labels: bug

#433 First sketch of XGBoost integration with Merlin Dataset
  .github/workflows/xgboost.yml
  Makefile
  merlin/models/xgb/__init__.py
  pyproject.toml
  requirements/xgboost.txt
  setup.py
  tests/conftest.py
  tests/unit/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: status/work-in-progress

#431 Moving loss- and metrics-calculation to model instead of the predicti…
  examples/01-Getting-started.ipynb
  examples/02-Merlin-Models-and-NVTabular-integration.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/combinators.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/metrics/ranking.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/multi.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/regression.py
  merlin/models/tf/prediction_tasks/retrieval.py
  merlin/models/tf/utils/mixins.py
  merlin/models/tf/utils/repr_utils.py
  merlin/models/tf/utils/search_utils.py
  tests/unit/tf/blocks/core/test_index.py
  tests/unit/tf/blocks/core/test_transformations.py
  tests/unit/tf/examples/test_01_getting_started.py
  tests/unit/tf/examples/test_02_dataschema.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/examples/test_06_advanced_own_architecture.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_benchmark.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
  tests/unit/tf/prediction_tasks/test_next_item.py
  tests/unit/tf/utils/test_batch.py
Labels: enhancement, status/needs-review

#465 Replace use of removeprefix function which requires Python 3.9+
  merlin/models/xgb/__init__.py
Labels: bug

#470 Remove tf.test.is_gpu_available call
  merlin/models/utils/nvt_utils.py
Labels: chore
