Repository NVIDIA-Merlin/models, pull requests merged in 2022-06, with the labels that each got.

#476 Move tabular tests from test_core to test_tabular
  tests/unit/tf/blocks/core/test_tabular.py
  tests/unit/tf/test_core.py
Labels: chore

#492 Fix dataloader docstring
  merlin/models/tf/dataset.py
  merlin/models/torch/dataset.py
Labels: documentation

#493 Fix to pass shuffle argument to dataloader
  merlin/models/tf/models/base.py
Labels: bug

#501 Remove `Block.to_model`
  examples/03-Exploring-different-models.ipynb
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/models/base.py
  tests/unit/tf/blocks/test_mlp.py
  tests/unit/tf/models/test_base.py
Labels: breaking

#506 Add a GA workflow that requires labels on PR's
  .github/workflows/require-label.yaml
Labels: ci

#505 Fix prediction task documentation
  merlin/models/tf/prediction_tasks/base.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/regression.py
Labels: documentation

#510 Fix pytest marker for integration tests.
  pyproject.toml
  tests/conftest.py
Labels: chore

#466 XGBoost - Switch to dask API
  merlin/models/xgb/__init__.py
  tests/conftest.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement

#511 Fixes computing metrics each N steps during training and adding regularization_loss metric
  merlin/models/tf/metrics/ranking.py
  merlin/models/tf/models/base.py
  tests/integration/tf/test_ci_01_getting_started.py
  tests/integration/tf/test_ci_02_dataschema.py
  tests/integration/tf/test_ci_03_exploring_different_models.py
  tests/unit/tf/examples/test_01_getting_started.py
  tests/unit/tf/examples/test_02_dataschema.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/examples/test_06_advanced_own_architecture.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
  tests/unit/tf/prediction_tasks/test_next_item.py
Labels: bug

#512 Update to refer to merlin-tensorflow container
  examples/01-Getting-started.ipynb
  examples/02-Merlin-Models-and-NVTabular-integration.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/README.md
Labels: documentation, status/needs-review

#513 Creating test fixture to reset state of TF Keras graph before each test
  tests/unit/tf/_conftest.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
Labels: area/tests, size/S, skip-changelog

#481 Add tests for calling filter block when output returns empty
  tests/unit/tf/blocks/core/test_tabular.py
Labels: chore

#516 Update URLs to Criteo datasets
  merlin/datasets/advertising/criteo/dataset.py
Labels: documentation

#478 Propagate schema to branches if needed in ParallelBlock
  merlin/models/tf/blocks/core/combinators.py
  tests/unit/tf/blocks/core/test_combinators.py
Labels: bug

#517 Handle ParallelBlock in Model.from_block
  merlin/models/tf/models/base.py
  tests/unit/tf/blocks/core/test_combinators.py
Labels: bug

#519 Add tests for train_metrics_steps ensuring we can control the frequency of computing metrics
  tests/unit/tf/models/test_base.py
Labels: chore

#514 Refactored top-k metrics and created TopKMetricsAggregator for optimized metrics computation
  merlin/models/tf/__init__.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/prediction_tasks/retrieval.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/models/test_retrieval.py
Labels: enhancement, status/needs-review, P1

#472 Use standard Keras embedding layers inside `EmbeddingFeatures` block
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: enhancement

#508 add usecase with pretrained embeddings
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  tests/unit/tf/examples/test_usecase_pretrained_embeddings.py
Labels: documentation, area/examples

#528 XGBoost - Use DaskDeviceQuantileDMatrix with GPU Training
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement

#532 EmbeddingFeatures - Move embedding table creation from build to __init__
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/inputs/test_embedding.py
Labels: bug

#531 XGBoost - Train/eval with features from schema passed in to the constructor
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement

#538 XGBoost - Add evals argument to fit to support eval on datasets other than training
  merlin/models/xgb/__init__.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement

#522 add xgboost example
  examples/07-Train-an-xgboost-model-using-the-Merlin-Models-API.ipynb
  tests/integration/tf/test_ci_07_xgboost_integration.py
Labels: examples
