Repository NVIDIA-Merlin/models, pull requests merged in 2022-04, with the labels that each got.

#362 First design of popularity correction
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/core/base.py
  merlin/models/tf/blocks/core/transformations.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/retrieval.py
  tests/tf/blocks/core/test_transformations.py
  tests/tf/blocks/retrieval/test_two_tower.py
  tests/tf/models/test_retrieval.py
  tests/tf/prediction_tasks/test_next_item.py
Labels: status/needs-review

#389 Fix top-k recommender to return correct top-k relevant items.
  merlin/models/tf/models/base.py
  tests/tf/blocks/core/test_index.py
Labels: bug, area/api

#394 Update `testbook` tests to use absolute notebook paths
  tests/conftest.py
  tests/tf/examples/__init__.py
  tests/tf/examples/test_01_getting_started.py
  tests/tf/examples/test_02_dataschema.py
  tests/tf/examples/test_04_export_ranking_models.py
  tests/tf/examples/test_05_export_retrieval_model.py
  tests/tf/examples/test_06_advanced_own_architecture.py
Labels: area/tests
