Repository NVIDIA-Merlin/models, pull requests merged in 2022-12, with the labels that each got.

#886 Save output schema of model and add save method to `Encoder`
  merlin/models/tf/core/encoder.py
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#845 Use merlin-dataloader package
  .github/workflows/tensorflow.yml
  examples/05-Retrieval-Model.ipynb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  merlin/datasets/synthetic.py
  merlin/models/loader/backend.py
  merlin/models/loader/dataframe_iter.py
  merlin/models/loader/tf_utils.py
  merlin/models/loader/utils.py
  merlin/models/tf/__init__.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/tensor.py
  merlin/models/tf/utils/testing_utils.py
  merlin/models/torch/dataset.py
  merlin/models/torch/utils/torch_utils.py
  requirements/base.txt
  tests/common/tf/retrieval/retrieval_utils.py
  tests/unit/datasets/test_synthetic.py
  tests/unit/tf/blocks/test_interactions.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/core/test_index.py
  tests/unit/tf/core/test_prediction.py
  tests/unit/tf/horovod/test_horovod.py
  tests/unit/tf/inputs/test_base.py
  tests/unit/tf/inputs/test_tabular.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
  tests/unit/tf/test_loader.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_features.py
  tests/unit/tf/transforms/test_negative_sampling.py
  tests/unit/tf/transforms/test_sequence.py
  tests/unit/torch/test_dataset.py
  tox.ini
Labels: area/data-loading, chore

#916 Restore documentation build
  .github/workflows/datasets.yml
  .github/workflows/docs-build.yaml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
  .pre-commit-config.yaml
  tox.ini
Labels: chore, skip-changelog

#909 Fix the inference of transformer-based models trained with masked language modeling
  merlin/models/tf/__init__.py
  merlin/models/tf/transformers/block.py
  merlin/models/tf/transformers/transforms.py
  merlin/models/tf/transforms/sequence.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_sequence.py
Labels: bug

#920 Pass `task="binary"` to binary metrics to handle latest torchmetrics
  merlin/models/torch/model/prediction_task.py
  requirements/pytorch.txt
Labels: ci

#902 Adding official support to Multi-Task Learning models: MMOE, CGC and PLE with fixes and improvements
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/experts.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
Labels: bug, enhancement

#921 fix dtype error due to date column in ecommerce-session-based-next-item-prediction-for-fashion nb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
Labels: examples

#922 fix typos in docstrings
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/outputs/contrastive.py
Labels: documentation

#925 Publish Release Draft on release branch builds
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: ci

#931 Set upper-bound on numpy version in tox.ini
  merlin/models/tf/loader.py
  tox.ini
Labels: ci

#930 Enable model serialization with pickle
  merlin/models/io.py
  tests/unit/tf/models/test_base.py
Labels: bug

#891 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: enhancement, ci, chore, gpuCI-test-this

#934 adding workflow for gpu ci on gha runner
  .github/workflows/gpu-ci.yml
Labels: ci, chore

#936 Update tox.ini gpu test to use github actions
  requirements/test.txt
  tox.ini
Labels: ci, chore

#937 Removing from Loader unused 'transform' and 'multi_target_as_dict' constructor args
  merlin/models/tf/loader.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/test_loader.py
Labels: chore

#933 pytest mark notebooks
  tests/unit/tf/examples/test_01_getting_started.py
  tests/unit/tf/examples/test_02_dataschema.py
  tests/unit/tf/examples/test_03_exploring_different_models.py
  tests/unit/tf/examples/test_04_export_ranking_models.py
  tests/unit/tf/examples/test_05_export_retrieval_model.py
  tests/unit/tf/examples/test_06_advanced_own_architecture.py
  tests/unit/tf/examples/test_07_train_traditional_models.py
  tests/unit/tf/examples/test_usecase_accelerate_training_by_lazyadam.py
  tests/unit/tf/examples/test_usecase_data_parallel.py
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
  tests/unit/tf/examples/test_usecase_incremental_training_layer_freezing.py
  tests/unit/tf/examples/test_usecase_pretrained_embeddings.py
  tests/unit/tf/examples/test_usecase_retrieval_with_hpo.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: chore

#938 Use tf.function for list column operations
  merlin/models/tf/outputs/topk.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/utils/tf_utils.py
  requirements/test.txt
  tests/unit/tf/test_loader.py
Labels: bug, area/tensorflow, ci

#904 Ensure saved model input signature contains only required features
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  merlin/models/loader/backend.py
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/examples/test_usecase_ecommerce_session_based.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_negative_sampling.py
Labels: enhancement

#932 add clarification and example usage in contrastive class docstrings
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/outputs/contrastive.py
Labels: documentation

#927 Fix the serialization of `SequenceSummary` block
  merlin/models/tf/transformers/transforms.py
  tests/unit/tf/transformers/test_block.py
Labels: bug, P0

#939 Add downstream repo tests
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  tox.ini
Labels: area/tests, ci
