Repository NVIDIA-Merlin/models, pull requests merged in 2023-02, with the labels that each got.

#972 Update branch name extraction for tag builds
  .github/workflows/cpu-horovod.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/datasets.yml
  .github/workflows/gpu-ci.yml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
Labels: ci

#968 add get_config() to AverageEmbeddingsByWeightFeature class
  merlin/models/tf/inputs/embedding.py
Labels: bug, enhancement, P0

#967 Update 05-Retrieval-Model.ipynb
  examples/05-Retrieval-Model.ipynb
Labels: examples

#969 Fixes support of sequential continuous features for sequential and non-sequential models
  merlin/models/tf/core/aggregation.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/transforms/tensor.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/blocks/test_mlp.py
  tests/unit/tf/transformers/test_block.py
Labels: bug, enhancement, P0

#973 fix training a sequential model with AverageEmbeddingsByWeightFeature
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/embedding.py
  tests/unit/tf/models/test_base.py
Labels: bug, P0

#979 Makes ColumnBasedSampleWeight serializable
  merlin/models/tf/outputs/block.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/outputs/test_block.py
Labels: bug

#975 enhancing the next-item prediction notebook documentation
  examples/usecases/transformers-next-item-prediction.ipynb
Labels: chore, examples

#980 Add unit tests for SOKEmbedding
  merlin/models/tf/distributed/backend.py
  merlin/models/tf/distributed/embedding.py
  tests/unit/tf/horovod/test_embedding.py
  tox.ini
Labels: area/tests, chore

#983 Fixes lower train metrics when using Keras Masking (SequenceMaskRandom, SequenceMaskLast)
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_base.py
Labels: bug

#991 Fix BroadcastToSequence to enable context features in sequential models
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/transforms/tensor.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_features.py
  tests/unit/tf/transforms/test_sequence.py
Labels: bug

#995 Bump the versions of precommit hook packages
  .pre-commit-config.yaml
  README.md
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/core/tabular.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/outputs/topk.py
  merlin/models/tf/transformers/block.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/utils/tf_utils.py
  merlin/models/torch/utils/data_utils.py
  tests/common/tf/retrieval/retrieval_utils.py
  tests/unit/tf/blocks/test_cross.py
  tests/unit/tf/blocks/test_optimizer.py
  tests/unit/tf/experimental/test_sample_weight.py
  tests/unit/tf/metrics/test_metrics_topk.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_sampling.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_noise.py
  tests/unit/tf/transforms/test_sequence.py
  tests/unit/torch/tabular/test_transformations.py
Labels: chore

#992 Renaming ProcessList to PrepareFeatures
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/transforms/tensor.py
  merlin/models/tf/utils/testing_utils.py
  tests/unit/datasets/test_synthetic.py
  tests/unit/tf/blocks/retrieval/test_two_tower.py
  tests/unit/tf/blocks/test_interactions.py
  tests/unit/tf/inputs/test_base.py
  tests/unit/tf/inputs/test_continuous.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/transforms/test_negative_sampling.py
  tests/unit/tf/transforms/test_sequence.py
Labels: enhancement

#1001 Wrap SequencePredictLast with tf.function
  merlin/models/tf/transforms/sequence.py
  tests/unit/tf/blocks/test_mlp.py
Labels: ci

#998 Updates in the text of MTL example notebook
  examples/usecases/ranking_with_multitask_learning.ipynb
Labels: examples

#1004 Fix nvtabular import in validate_dataset
  merlin/models/utils/misc_utils.py
Labels: chore

#1006 Add version specifier for `transformers` dependency
  requirements/transformers.txt
Labels: ci

#1002 Save and load LightFM model and schemas
  merlin/models/io.py
  merlin/models/lightfm/__init__.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/models/base.py
  merlin/models/utils/dataset.py
  merlin/models/xgb/__init__.py
  tests/unit/lightfm/test_lightfm.py
Labels: enhancement

#1007 Increase tolerance in retrieval transformer test and set random seed
  tests/unit/tf/transformers/test_block.py
Labels: ci
