Repository NVIDIA-Merlin/models, pull requests merged in 2023-04, with the labels that each got.

#1055 add concurrency param to kill Github Action jobs when new commits come in
  .github/workflows/cpu-horovod.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/datasets.yml
  .github/workflows/docs-build.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/implicit.yml
  .github/workflows/multi-gpu-ci.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
Labels: ci, chore

#1057 Update dataset test to expect schema.pbtxt in output
  .github/workflows/multi-gpu-ci.yml
  tests/unit/datasets/test_ecommerce.py
Labels: ci, chore

#1053 Fix import gpu without support
  merlin/models/tf/utils/tf_utils.py
  merlin/models/utils/nvt_utils.py
  tests/unit/datasets/test_synthetic.py
  tests/unit/tf/blocks/retrieval/test_matrix_factorization.py
  tests/unit/tf/blocks/retrieval/test_two_tower.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/xgb/test_xgboost.py
Labels: enhancement, ci, chore

#1060 Install `wheel` package to enable legacy install method of LightFM package
  .github/workflows/lightfm.yml
Labels: ci

#1052 Fixes model.batch_predict() which was not working with ModelOuput
  merlin/models/tf/models/base.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/outputs/block.py
  merlin/models/tf/utils/batch_utils.py
  tests/unit/tf/utils/test_batch.py
Labels: bug

#1049 Add Transformers4Rec repo test
  .github/workflows/cpu-t4r.yml
  tox.ini
Labels: enhancement, ci

#1051 Refactory/fix of sampled softmax to add logQ correction
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/outputs/contrastive.py
  merlin/models/tf/outputs/sampling/base.py
  merlin/models/tf/outputs/sampling/popularity.py
  merlin/models/tf/transforms/bias.py
  tests/unit/tf/outputs/test_contrastive.py
Labels: bug, enhancement

#1045 MM transformer training and serving example
  .github/workflows/tensorflow.yml
  examples/usecases/transformers-next-item-prediction.ipynb
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
  tox.ini
Labels: examples

#1064 Disable keras optimizer module change in SOK with `use_legacy_optimizer`
  merlin/models/tf/distributed/backend.py
Labels: chore

#1020 Remove out-dated pytorch backend for now
  .github/workflows/pytorch.yml
  merlin/models/torch/__init__.py
  merlin/models/torch/block/__init__.py
  merlin/models/torch/block/base.py
  merlin/models/torch/block/mlp.py
  merlin/models/torch/features/__init__.py
  merlin/models/torch/features/base.py
  merlin/models/torch/features/continuous.py
  merlin/models/torch/features/embedding.py
  merlin/models/torch/features/tabular.py
  merlin/models/torch/losses.py
  merlin/models/torch/model/__init__.py
  merlin/models/torch/model/base.py
  merlin/models/torch/model/prediction_task.py
  merlin/models/torch/tabular/__init__.py
  merlin/models/torch/tabular/aggregation.py
  merlin/models/torch/tabular/base.py
  merlin/models/torch/tabular/transformations.py
  merlin/models/torch/typing.py
  merlin/models/torch/utils/__init__.py
  merlin/models/torch/utils/data_utils.py
  merlin/models/torch/utils/examples_utils.py
  merlin/models/torch/utils/torch_utils.py
  tests/unit/torch/__init__.py
  tests/unit/torch/_conftest.py
  tests/unit/torch/block/__init__.py
  tests/unit/torch/block/test_base.py
  tests/unit/torch/block/test_mlp.py
  tests/unit/torch/features/__init__.py
  tests/unit/torch/features/test_continuous.py
  tests/unit/torch/features/test_embedding.py
  tests/unit/torch/features/test_tabular.py
  tests/unit/torch/model/__init__.py
  tests/unit/torch/model/test_head.py
  tests/unit/torch/model/test_model.py
  tests/unit/torch/tabular/__init__.py
  tests/unit/torch/tabular/test_aggregation.py
  tests/unit/torch/tabular/test_tabular.py
  tests/unit/torch/tabular/test_transformations.py
  tests/unit/torch/test_dataloader_utils.py
  tests/unit/torch/test_losses.py
  tests/unit/torch/test_public_api.py
  tests/unit/torch/utils/__init__.py
Labels: chore

#1066 Update horovod test to use main branch of SOK
  examples/usecases/multi-gpu/install_sparse_operation_kit.sh
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: ci, chore

#1062 implement review suggestions
  examples/usecases/transformers-next-item-prediction.ipynb
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: examples

#1074 remove blossom-ci
  .github/workflows/blossom-ci.yml
Labels: ci, chore

#1069 Update requirements for Merlin packages to minimum version of 23.04
  requirements/base.txt
Labels: chore

#1067 Skip gpu tests on PR closed event
  .github/workflows/gpu-ci.yml
  .github/workflows/multi-gpu-ci.yml
Labels: ci, chore

#1075 Add publish step for conda package
  .github/workflows/packages.yaml
  .github/workflows/tensorflow.yml
  MANIFEST.in
  conda/recipes/meta.yaml
Labels: chore
