Repository NVIDIA-Merlin/models, pull requests merged in 2023-01, with the labels that each got.

#944 Add a legal statement to the notebooks
  examples/01-Getting-started.ipynb
  examples/02-Merlin-Models-and-NVTabular-integration.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/07-Train-traditional-ML-models-using-the-Merlin-Models-API.ipynb
  examples/usecases/accelerate-training-of-large-embedding-tables-by-LazyAdam.ipynb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  examples/usecases/incremental-training-with-layer-freezing.ipynb
  examples/usecases/multi-gpu-data-parallel-training.ipynb
  examples/usecases/retrieval-with-hyperparameter-optimization.ipynb
  examples/usecases/transformers-next-item-prediction.ipynb
Labels: documentation, skip-changelog

#926 Add value_count property if output is fixed size tensor
  merlin/models/tf/models/base.py
  tests/unit/tf/models/test_base.py
Labels: enhancement

#943 Fix use case t4rec
  examples/usecases/transformers-next-item-prediction.ipynb
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: documentation, chore, examples

#911 update the 7-Train-traditional-ML-models-using-the-Merlin-Models-API notebook based on customer feedback in #906
  examples/07-Train-traditional-ML-models-using-the-Merlin-Models-API.ipynb
Labels: documentation, examples

#949 Add Tensorflow 2.10 tests for examples
  .github/workflows/tensorflow.yml
Labels: enhancement, ci, examples

#941 add gcp label to jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: ci

#947 fix oom issue in example unit tests
  examples/usecases/accelerate-training-of-large-embedding-tables-by-LazyAdam.ipynb
  examples/usecases/incremental-training-with-layer-freezing.ipynb
  tests/unit/tf/examples/test_usecase_accelerate_training_by_lazyadam.py
  tests/unit/tf/examples/test_usecase_incremental_training_layer_freezing.py
Labels: area/tests, chore

#915 Restore API documentation
  docs/source/api.rst
  requirements/docs.txt
  tox.ini
Labels: documentation

#912 Adjust synthetic dataset generator to use Merlin dtypes (in schemas etc)
  merlin/datasets/ecommerce/booking/transformed/schema.pbtxt
  merlin/datasets/entertainment/movielens/100k/schema.pbtxt
  merlin/datasets/entertainment/movielens/25m/schema.pbtxt
  merlin/datasets/entertainment/music_streaming/schema.json
  merlin/datasets/synthetic.py
  tox.ini
Labels: chore

#948 Creating a multi-task learning example for ranking models
  examples/images/mtl_architectures.png
  examples/usecases/ranking_with_multitask_learning.ipynb
  merlin/datasets/entertainment/tenrec_video/__init__.py
  merlin/datasets/entertainment/tenrec_video/schema.pbtxt
  merlin/datasets/synthetic.py
  tests/unit/tf/examples/test_usecase_ranking_with_multitask_learning.py
Labels: enhancement, examples

#958 Add horovod CPU tests to github actions
  .github/workflows/cpu-horovod.yml
  merlin/models/tf/models/base.py
  requirements/horovod-cpu-environment.yml
  tox.ini
Labels: ci, chore
