Repository NVIDIA-Merlin/models, pull requests merged in 2023-07, with the labels that each got.

#1168 Rename and update tox environments
  .github/workflows/cpu-horovod.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/cpu-t4r.yml
  .github/workflows/gpu-multi.yml
  .github/workflows/gpu.yml
  tox.ini
Labels: ci

#1167 Add fixture to cleanup dataloader threads
  tests/conftest.py
Labels: chore

#1166 Replace import of collections.Sequence with collections.abc.Sequence
  merlin/models/tf/core/tabular.py
  merlin/models/tf/inputs/embedding.py
Labels: bug

#1162 Add DLRM block
  merlin/models/torch/__init__.py
  merlin/models/torch/blocks/dlrm.py
  merlin/models/torch/router.py
  merlin/models/torch/transforms/agg.py
  tests/unit/torch/blocks/test_dlrm.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/outputs/test_tabular.py
Labels: enhancement, area/pytorch

#1170 Remove link, and introduce ShortcutBlock + ResidualBlock
  merlin/models/torch/__init__.py
  merlin/models/torch/block.py
  merlin/models/torch/blocks/dlrm.py
  merlin/models/torch/container.py
  merlin/models/torch/link.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_container.py
  tests/unit/torch/test_link.py
Labels: enhancement, area/pytorch

#1172 Adding CrossBlock (used in DCN-v2)
  merlin/models/torch/blocks/cross.py
  tests/unit/torch/blocks/test_cross.py
Labels: enhancement, area/pytorch

#1171 Add DLRM Model
  merlin/models/torch/__init__.py
  merlin/models/torch/models/base.py
  merlin/models/torch/models/ranking.py
  merlin/models/torch/utils/module_utils.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/models/test_ranking.py
Labels: enhancement, area/pytorch

#1169 Fixes retrieval encoders when query / item features have dense list features
  merlin/datasets/entertainment/music_streaming/schema.json
  merlin/models/tf/core/encoder.py
  merlin/models/tf/core/index.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/batch_utils.py
  tests/unit/tf/models/test_retrieval.py
Labels: bug

#1175 Change default loss in BinaryOutput to BCELoss
  merlin/models/torch/outputs/classification.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/outputs/test_classification.py
Labels: bug, area/pytorch

#1178 Adding ToTuple
  merlin/models/torch/schema.py
  merlin/models/torch/transforms/tuple.py
  tests/unit/torch/transforms/test_tuple.py
Labels: enhancement, area/pytorch

#1177 Add padding operator to the PyTorch API
  merlin/models/torch/transforms/sequences.py
  tests/unit/torch/transforms/test_sequences.py
Labels: enhancement, area/pytorch

#1181 Adding validation_step and test_step to Model
  .gitignore
  merlin/models/torch/models/base.py
  tests/unit/torch/models/test_base.py
Labels: enhancement, area/pytorch

#1179 Rename Schema Inspection names in the torch schema module
  merlin/models/torch/__init__.py
  merlin/models/torch/batch.py
  merlin/models/torch/block.py
  merlin/models/torch/blocks/mlp.py
  merlin/models/torch/inputs/select.py
  merlin/models/torch/schema.py
  tests/unit/torch/inputs/test_select.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_router.py
  tests/unit/torch/test_schema.py
Labels: enhancement

#1182 Adding ToTuple function
  merlin/models/torch/transforms/tuple.py
  tests/unit/torch/transforms/test_tuple.py
Labels: enhancement, area/pytorch

#1183 Adding ElementWiseSum
  merlin/models/torch/transforms/agg.py
  tests/unit/torch/transforms/test_agg.py
Labels: enhancement, area/pytorch, status/needs-review

#1158 Add CategoricalOutput
  merlin/models/torch/__init__.py
  merlin/models/torch/inputs/embedding.py
  merlin/models/torch/outputs/base.py
  merlin/models/torch/outputs/classification.py
  merlin/models/torch/outputs/regression.py
  merlin/models/torch/outputs/tabular.py
  merlin/models/torch/router.py
  merlin/models/torch/transforms/bias.py
  merlin/models/torch/utils/traversal_utils.py
  tests/unit/torch/outputs/test_base.py
  tests/unit/torch/outputs/test_classification.py
  tests/unit/torch/outputs/test_regression.py
  tests/unit/torch/outputs/test_tabular.py
  tests/unit/torch/transforms/test_bias.py
  tests/unit/torch/utils/test_traversal_utils.py
Labels: enhancement, area/pytorch, status/needs-review

#1160 Remove examples spanning multiple repos / promote ecommerce session-based example
  examples/08-Train-a-model-for-session-based-next-item-prediction.ipynb
  examples/usecases/transformers-next-item-prediction-with-pretrained-embeddings.ipynb
  examples/usecases/transformers-next-item-prediction.ipynb
  tests/benchmark/test_asvdb_transformers_next_item_prediction.py
  tests/unit/tf/examples/test_08_session_based_next_item_prediction.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction_with_pretrained_embeddings.py
Labels: examples

#1184 Making input- and output-block lazy to allow for nesting
  merlin/models/torch/inputs/tabular.py
  merlin/models/torch/outputs/tabular.py
  merlin/models/torch/router.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/outputs/test_tabular.py
  tests/unit/torch/test_router.py
Labels: enhancement, area/pytorch, status/needs-review

#1189 Update docs theme from `sphinx_rtd_theme` to `sphinx_book_theme`
  docs/source/_static/NVIDIA-LogoBlack.svg
  docs/source/_static/NVIDIA-LogoWhite.svg
  docs/source/_static/css/custom.css
  docs/source/_static/css/versions.css
  docs/source/_static/favicon.png
  docs/source/_static/js/rtd-version-switcher.js
  docs/source/_templates/layout.html
  docs/source/_templates/merlin-ecosystem.html
  docs/source/_templates/versions.html
  docs/source/conf.py
  merlin/models/tf/__init__.py
  requirements/docs.txt
  requirements/tensorflow.txt
Labels: documentation

#1185 Add DCN Model
  merlin/models/torch/__init__.py
  merlin/models/torch/blocks/cross.py
  merlin/models/torch/models/ranking.py
  tests/unit/torch/models/test_ranking.py
Labels: enhancement, area/pytorch

#1188 Enabling data-parallel multi-GPU training
  .github/workflows/cpu-horovod.yml
  .github/workflows/gpu-multi.yml
  .github/workflows/gpu.yml
  merlin/models/torch/__init__.py
  merlin/models/torch/models/base.py
  merlin/models/torch/models/ranking.py
  pyproject.toml
  pytest.ini
  tests/integration/torch/__init__.py
  tests/integration/torch/test_multi_gpu.py
  tests/unit/torch/models/test_base.py
  tox.ini
Labels: enhancement, area/pytorch

#1191 Adding ContrastiveOutput
  merlin/models/torch/outputs/classification.py
  merlin/models/torch/outputs/contrastive.py
  merlin/models/torch/outputs/sampling/__init__.py
  merlin/models/torch/outputs/sampling/in_batch.py
  merlin/models/torch/outputs/sampling/popularity.py
  tests/unit/torch/outputs/sampling/__init__.py
  tests/unit/torch/outputs/sampling/test_in_batch.py
  tests/unit/torch/outputs/sampling/test_popularity.py
  tests/unit/torch/outputs/test_constrastive.py
Labels: enhancement, area/pytorch, status/needs-review

#1186 Enable lazy module initialization from schema for any module
  merlin/models/torch/batch.py
  merlin/models/torch/inputs/embedding.py
  merlin/models/torch/inputs/select.py
  merlin/models/torch/inputs/tabular.py
  merlin/models/torch/outputs/classification.py
  merlin/models/torch/outputs/regression.py
  merlin/models/torch/outputs/tabular.py
  merlin/models/torch/router.py
  merlin/models/torch/schema.py
  merlin/models/torch/transforms/tuple.py
  tests/unit/torch/inputs/test_embedding.py
  tests/unit/torch/inputs/test_select.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/outputs/test_classification.py
  tests/unit/torch/outputs/test_regression.py
  tests/unit/torch/test_router.py
  tests/unit/torch/test_schema.py
Labels: enhancement

#1187 Making it possible to set optimizer and scheduler instances via PyTorch model properties for training
  merlin/models/torch/models/base.py
  tests/unit/torch/models/test_base.py
Labels: enhancement, area/pytorch

#1196 Apply rename to initialize_from_schema to ContrastiveOutput
  merlin/models/torch/outputs/contrastive.py
  tests/unit/torch/outputs/test_constrastive.py
Labels: bug, area/pytorch, status/needs-review

#1195 Adding BroadcastToSequence
  merlin/models/torch/__init__.py
  merlin/models/torch/transforms/sequences.py
  tests/unit/torch/transforms/test_sequences.py
Labels: enhancement, area/pytorch, status/needs-review

#1197 Adding * selection of schema
  merlin/models/torch/schema.py
  tests/unit/torch/test_schema.py
Labels: bug, area/pytorch

#1192 Introducing BatchBlock
  merlin/models/torch/__init__.py
  merlin/models/torch/batch.py
  merlin/models/torch/block.py
  merlin/models/torch/models/base.py
  merlin/models/torch/predict.py
  merlin/models/torch/transforms/sequences.py
  merlin/models/torch/utils/module_utils.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/test_batch.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_predict.py
Labels: enhancement, area/pytorch, status/needs-review

#1199 Rename setup_schema to initialize_from_schema in TabularPadding
  merlin/models/torch/transforms/sequences.py
Labels: bug, area/pytorch

#1194 Add functional-methods to make it easier to transform blocks & models.
  merlin/models/torch/container.py
  tests/unit/torch/test_container.py
Labels: enhancement, area/pytorch, status/needs-review

#1200 Adding sequence-defaults in TabularInputBlock
  merlin/models/torch/__init__.py
  merlin/models/torch/batch.py
  merlin/models/torch/block.py
  merlin/models/torch/blocks/dlrm.py
  merlin/models/torch/inputs/tabular.py
  merlin/models/torch/outputs/tabular.py
  merlin/models/torch/router.py
  merlin/models/torch/schema.py
  merlin/models/torch/transforms/agg.py
  merlin/models/torch/transforms/sequences.py
  tests/unit/torch/blocks/test_dlrm.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/outputs/test_tabular.py
  tests/unit/torch/transforms/test_sequences.py
Labels: enhancement, area/pytorch

#1193 Adding CrossAttentionBlock
  merlin/models/torch/__init__.py
  merlin/models/torch/blocks/attention.py
  merlin/models/torch/schema.py
  tests/unit/torch/blocks/test_attention.py
Labels: enhancement, area/pytorch, status/needs-review

#1203 Add generic map that works on any Module
  merlin/models/torch/__init__.py
  merlin/models/torch/container.py
  merlin/models/torch/functional.py
  tests/unit/torch/test_container.py
  tests/unit/torch/test_functional.py
Labels: enhancement, area/pytorch

#1202 Add TabularPredictNext for causal item prediction task
  merlin/models/torch/transforms/sequences.py
  tests/unit/torch/transforms/test_sequences.py
Labels: enhancement

#1198 Makes RetrievalModelV2 support item tower with transforms (e.g. pre-trained embeddings)
  examples/05-Retrieval-Model.ipynb
  merlin/models/tf/core/encoder.py
  merlin/models/tf/models/base.py
  merlin/models/tf/utils/batch_utils.py
  tests/integration/torch/__init__.py
  tests/unit/tf/models/test_retrieval.py
Labels: enhancement
