Repository NVIDIA-Merlin/models, pull requests merged in 2023-05, with the labels that each got.

#1080 Add Workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#1086 Extend ContrastiveOutput to support sequential encoders
  merlin/models/tf/outputs/contrastive.py
  tests/unit/tf/transformers/test_block.py
Labels: bug, area/retrieval, area/session-based

#1098 Change tf.keras.optimizers.Adagrad() to tf.keras.optimizers.legacy.Adagrad()
  examples/03-Exploring-different-models.ipynb
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  examples/usecases/multi-gpu-data-parallel-training.ipynb
  merlin/models/tf/blocks/optimizer.py
  merlin/models/tf/models/ranking.py
  tests/common/tf/retrieval/retrieval_utils.py
  tests/unit/tf/models/test_ranking.py
Labels: P0, ci, examples

#1087 Introducing Block
  .github/workflows/pytorch.yml
  Makefile
  merlin/models/torch/__init__.py
  merlin/models/torch/batch.py
  merlin/models/torch/block.py
  merlin/models/torch/container.py
  merlin/models/torch/utils/__init__.py
  merlin/models/torch/utils/module_utils.py
  merlin/models/torch/utils/torchscript_utils.py
  tests/unit/torch/__init__.py
  tests/unit/torch/test_batch.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_container.py
  tests/unit/torch/utils/__init__.py
  tests/unit/torch/utils/test_module_utils.py
  tests/unit/torch/utils/test_torchscript_utils.py
Labels: enhancement, area/pytorch

#1083 Add dataloader pre-trained embeddings support to Merlin Models
  merlin/datasets/entertainment/music_streaming/schema.json
  merlin/datasets/testing/schema.json
  merlin/datasets/testing/sequence_testing/schema.json
  merlin/models/tf/__init__.py
  merlin/models/tf/blocks/mlp.py
  merlin/models/tf/core/aggregation.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/loader.py
  merlin/models/tf/outputs/sampling/popularity.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/regularization.py
  merlin/models/tf/transforms/sequence.py
  tests/unit/tf/blocks/test_dlrm.py
  tests/unit/tf/blocks/test_mlp.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_features.py
Labels: enhancement, status/needs-review

#1105 Skip installing dependencies in tox gpu test
  tox.ini
Labels: ci

#1101 [WIP] add docstrings in mms classes and functions
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/regression.py
  merlin/models/tf/prediction_tasks/retrieval.py
Labels: documentation, skip-base-branch-check

#1088 Adding ParallelBlock
  .github/workflows/pytorch.yml
  merlin/models/torch/__init__.py
  merlin/models/torch/block.py
  merlin/models/torch/container.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_container.py
Labels: enhancement, area/pytorch, status/blocked

#1100 update pretrained embs example
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  merlin/datasets/entertainment/movielens/100k/schema.json
  merlin/datasets/entertainment/movielens/100k/schema.pbtxt
  tests/unit/tf/examples/test_usecase_pretrained_embeddings.py
Labels: examples

#1106 Add docstrings
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/transforms/regularization.py
  merlin/models/tf/transforms/sequence.py
Labels: documentation, chore, skip-base-branch-check

#1118 Fixing ci skipping
  .github/workflows/cpu-horovod.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/cpu-t4r.yml
  .github/workflows/datasets.yml
  .github/workflows/gpu-multi.yml
  .github/workflows/gpu.yml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/pytorch.yml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
  ci/get_changed_backends.py
  merlin/models/utils/ci_utils.py
Labels: bug

#1095 Adding sample_batch & sample_features
  merlin/models/torch/batch.py
  tests/unit/torch/test_batch.py
Labels: enhancement, area/pytorch

#1121 Configure Prettier YAML/Markdown formatter for all files
  .github/ISSUE_TEMPLATE/--new-model-addition.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/submit-question.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/cpu-nvtabular.yml
  .github/workflows/cpu-systems.yml
  .github/workflows/cpu-t4r.yml
  .github/workflows/datasets.yml
  .github/workflows/docs-build.yaml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-multi.yml
  .github/workflows/gpu.yml
  .github/workflows/implicit.yml
  .github/workflows/lightfm.yml
  .github/workflows/lint.yml
  .github/workflows/pytorch.yml
  .github/workflows/release-drafter.yaml
  .github/workflows/tensorflow.yml
  .github/workflows/xgboost.yml
  .pre-commit-config.yaml
  CLA.md
  CONTRIBUTING.md
Labels: ci

#1123 increase tolerance threshold
  tests/unit/tf/transformers/test_block.py
Labels: ci, chore

#1091 Adding Link
  merlin/models/torch/block.py
  merlin/models/torch/container.py
  merlin/models/torch/link.py
  merlin/models/torch/registry.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_container.py
  tests/unit/torch/test_link.py
Labels: enhancement, area/pytorch, status/needs-review

#1115 Add RegressionOutput
  merlin/models/torch/__init__.py
  merlin/models/torch/outputs/regression.py
  tests/unit/torch/outputs/test_regression.py
Labels: enhancement, area/pytorch

#1124 Fix CI path detection for changed files
  merlin/models/xgb/__init__.py
  tests/conftest.py
Labels: bug, ci, chore

#1092 Adding simple aggregations: concat & stack
  merlin/models/torch/__init__.py
  merlin/models/torch/transforms/__init__.py
  merlin/models/torch/transforms/agg.py
  tests/unit/torch/transforms/__init__.py
  tests/unit/torch/transforms/test_agg.py
Labels: enhancement, area/pytorch, status/needs-review

#1109 Adding SchemaTrackingMixin
  merlin/models/torch/block.py
  merlin/models/torch/utils/schema_utils.py
  tests/unit/torch/test_block.py
  tests/unit/torch/utils/test_schema_utils.py
Labels: enhancement, area/pytorch

#1093 Adding MLPBlock
  merlin/models/torch/blocks/__init__.py
  merlin/models/torch/blocks/mlp.py
  merlin/models/torch/container.py
  merlin/models/torch/utils/module_utils.py
  tests/unit/torch/blocks/__init__.py
  tests/unit/torch/blocks/test_mlp.py
  tests/unit/torch/utils/test_module_utils.py
Labels: enhancement, area/pytorch, status/needs-review

#1125 Run unit tests separately from example and integration tests
  .github/workflows/gpu.yml
  tox.ini
Labels: ci
