Repository NVIDIA-Merlin/models, pull requests merged in 2023-03, with the labels that each got.

#1011 Use globally insatlled installed packages for GPU tests
  tests/unit/lightfm/test_lightfm.py
  tests/unit/tf/horovod/__init__.py
  tox.ini
Labels: ci, chore

#1003 Updates on MTL example text and illustration
  examples/images/mtl_architectures.png
  examples/usecases/ranking_with_multitask_learning.ipynb
  tests/unit/tf/outputs/test_block.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
Labels: enhancement, examples

#1012 Set random seed in each lightfm test
  tests/unit/lightfm/test_lightfm.py
Labels: ci, chore

#1014 Save and load Implicit model and schemas
  merlin/models/implicit/__init__.py
  tests/unit/implicit/test_implicit.py
  tests/unit/tf/outputs/test_classification.py
Labels: enhancement

#1009 Add multi-gpu github action tests using horovod
  .github/workflows/multi-gpu-ci.yml
  tox.ini
Labels: ci

#1017 Add a `pytest.ini` file to register custom markers (e.g. `notebook`)
  pytest.ini
Labels: ci, chore

#1018 Fixed DLRModel / DLRMBlock to accept bottom_block with dropout on top of MLPs
  merlin/models/tf/blocks/dlrm.py
  tests/unit/tf/models/test_ranking.py
Labels: bug

#999 Updates Models to support new dataloader format for lists (__values and __offsets in dict) and scalar (1D)
  .github/workflows/tensorflow.yml
  docs/source/api.rst
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/transformers-next-item-prediction.ipynb
  merlin/datasets/entertainment/movielens/1m/schema.pbtxt
  merlin/datasets/entertainment/music_streaming/schema.json
  merlin/datasets/synthetic.py
  merlin/datasets/testing/sequence_testing/schema.json
  merlin/models/tf/__init__.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/core/tabular.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/loader.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/outputs/contrastive.py
  merlin/models/tf/outputs/sampling/base.py
  merlin/models/tf/outputs/sampling/popularity.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/transforms/negative_sampling.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/transforms/tensor.py
  merlin/models/tf/utils/testing_utils.py
  merlin/models/tf/utils/tf_utils.py
  merlin/models/utils/schema_utils.py
  tests/common/tf/retrieval/retrieval_utils.py
  tests/unit/datasets/test_synthetic.py
  tests/unit/tf/blocks/test_interactions.py
  tests/unit/tf/core/test_base.py
  tests/unit/tf/core/test_combinators.py
  tests/unit/tf/core/test_encoder.py
  tests/unit/tf/inputs/test_block.py
  tests/unit/tf/inputs/test_continuous.py
  tests/unit/tf/inputs/test_embedding.py
  tests/unit/tf/inputs/test_tabular.py
  tests/unit/tf/models/test_base.py
  tests/unit/tf/models/test_ranking.py
  tests/unit/tf/models/test_retrieval.py
  tests/unit/tf/outputs/test_block.py
  tests/unit/tf/outputs/test_classification.py
  tests/unit/tf/outputs/test_contrastive.py
  tests/unit/tf/outputs/test_sampling.py
  tests/unit/tf/prediction_tasks/test_multi_task.py
  tests/unit/tf/test_loader.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_features.py
  tests/unit/tf/transforms/test_negative_sampling.py
  tests/unit/tf/transforms/test_sequence.py
  tests/unit/tf/transforms/test_tensor.py
  tox.ini
Labels: enhancement, chore

#1021 Fix dataset test due to metadata location change
  tests/unit/datasets/test_ecommerce.py
Labels: ci, chore

#863 Introduce SOKEmbedding using Sparse Operation Kit
  examples/usecases/multi-gpu/install_sparse_operation_kit.sh
  merlin/models/tf/distributed/backend.py
  merlin/models/tf/distributed/embedding.py
  requirements/horovod.txt
  tests/unit/tf/horovod/test_embedding.py
  tox.ini
Labels: enhancement, gpuCI-test-this

#1022 New design of the transformer API
  examples/usecases/transformers-next-item-prediction.ipynb
  merlin/models/tf/models/base.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/transformers/block.py
  merlin/models/tf/transformers/transforms.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/transformers/test_block.py
  tests/unit/tf/transforms/test_sequence.py
Labels: enhancement, area/tensorflow, P0, breaking, area/session-based

#1028 Convert Tensor to RaggedTensor in PrepareFeatures for list features
  merlin/models/tf/transforms/features.py
Labels: chore

#1023 Restoring tox.ini and .github/workflows/tensorflow.yml
  .github/workflows/tensorflow.yml
  tox.ini
Labels: ci, chore

#1030 Skip SOK tests if SOK is not installed
  merlin/models/tf/utils/testing_utils.py
  tests/unit/tf/horovod/test_embedding.py
Labels: ci, chore

#1031 set random seed in implicit tests
  tests/unit/implicit/test_implicit.py
Labels: ci, chore

#1029 Adds Support to embedding sequence_combiner for dense tensors
  merlin/datasets/ecommerce/booking/transformed/schema.pbtxt
  merlin/datasets/entertainment/music_streaming/schema.json
  merlin/datasets/synthetic.py
  merlin/datasets/testing/sequence_testing/schema.json
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/transforms/features.py
  merlin/models/tf/utils/tf_utils.py
  tests/unit/tf/inputs/test_embedding.py
Labels: bug

#1016 Tensorflow 2.11 support
  .github/workflows/tensorflow.yml
  examples/usecases/incremental-training-with-layer-freezing.ipynb
  merlin/models/tf/blocks/optimizer.py
  merlin/models/tf/models/base.py
  requirements/test.txt
  tests/unit/tf/blocks/test_optimizer.py
  tests/unit/tf/examples/test_usecase_incremental_training_layer_freezing.py
  tests/unit/tf/horovod/test_horovod.py
  tests/unit/tf/models/test_base.py
  tox.ini
Labels: enhancement, area/tensorflow

#1044 Test Model Reloading - Fixing some layers
  merlin/models/tf/blocks/optimizer.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/transforms/features.py
Labels: bug

#1040 Enable pickle of model with TensorFlow 2.11
  merlin/models/tf/models/base.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/transforms/features.py
  tests/unit/tf/core/test_combinators.py
  tests/unit/tf/experimental/test_sample_weight.py
  tests/unit/tf/models/test_base.py
Labels: chore
