Repository NVIDIA-Merlin/models, pull requests merged in 2023-06, with the labels that each got.

#1096 Adding RouterBlock
  merlin/models/torch/__init__.py
  merlin/models/torch/block.py
  merlin/models/torch/router.py
  merlin/models/torch/utils/selection_utils.py
  merlin/models/torch/utils/torchscript_utils.py
  tests/unit/torch/test_router.py
  tests/unit/torch/utils/test_selection_utils.py
Labels: enhancement, area/pytorch, status/needs-review

#1130 Install 'colorlog' in dev/test environment
  requirements/dev.txt
Labels: ci

#1133 Install dependencies in transformers4rec test
  tox.ini
Labels: ci

#1136 Pass mpi environment variable to tox
  tox.ini
Labels: ci

#1137 Update gpu tests workflow to run only examples (not integration) tests
  .github/workflows/gpu.yml
Labels: ci

#1134 Remove use of deprecated start_index from Categorify
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/transformers-next-item-prediction.ipynb
  merlin/datasets/ecommerce/booking/dataset.py
Labels: chore

#1129 fix gpu parallel nb example
  examples/usecases/multi-gpu-data-parallel-training.ipynb
Labels: bug

#1108 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci

#1139 Add TensorFlow 2.12 to test matrix
  .github/workflows/tensorflow.yml
Labels: ci

#1141 Update Optuna Hyperparameter Optimization notebook to match new Categorify
  examples/usecases/retrieval-with-hyperparameter-optimization.ipynb
Labels: chore

#1138 Skip dependencies in SOK installation
  examples/usecases/multi-gpu/install_sparse_operation_kit.sh
  merlin/models/tf/distributed/__init__.py
Labels: enhancement, ci, examples

#1122 Use `tf.matmul` instead of `np.dot` in `test_retrieval_transformer`
  tests/unit/tf/transformers/test_block.py
Labels: ci

#1042 asvdb tracking for next item prediction
  .github/workflows/tensorflow.yml
  examples/usecases/transformers-next-item-prediction.ipynb
  requirements/dev.txt
  tests/benchmark/test_asvdb_transformers_next_item_prediction.py
  tests/conftest.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction.py
Labels: ci

#1110 Add docstrings
  merlin/datasets/ecommerce/dressipi/dataset.py
  merlin/models/tf/blocks/dlrm.py
  merlin/models/tf/blocks/interaction.py
  merlin/models/tf/blocks/mlp.py
  merlin/models/tf/blocks/retrieval/base.py
  merlin/models/tf/core/combinators.py
  merlin/models/tf/core/encoder.py
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/continuous.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/loader.py
  merlin/models/tf/metrics/topk.py
  merlin/models/tf/models/base.py
  merlin/models/tf/models/ranking.py
  merlin/models/tf/models/retrieval.py
  merlin/models/tf/outputs/base.py
  merlin/models/tf/outputs/block.py
  merlin/models/tf/outputs/classification.py
  merlin/models/tf/outputs/sampling/in_batch.py
  merlin/models/tf/outputs/topk.py
  merlin/models/tf/prediction_tasks/classification.py
  merlin/models/tf/prediction_tasks/next_item.py
  merlin/models/tf/prediction_tasks/regression.py
  merlin/models/tf/prediction_tasks/retrieval.py
  merlin/models/tf/transforms/regularization.py
  merlin/models/tf/transforms/sequence.py
  merlin/models/tf/utils/testing_utils.py
  merlin/models/tf/utils/tf_utils.py
  merlin/models/torch/batch.py
Labels: documentation, enhancement

#1116 Build docs for stable branch and make default
  .github/workflows/docs-sched-rebuild.yaml
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/source/conf.py
  docs/source/index.rst
  examples/02-Merlin-Models-and-NVTabular-integration.ipynb
  examples/03-Exploring-different-models.ipynb
  examples/04-Exporting-ranking-models.ipynb
  examples/05-Retrieval-Model.ipynb
  examples/06-Define-your-own-architecture-with-Merlin-Models.ipynb
  examples/usecases/accelerate-training-of-large-embedding-tables-by-LazyAdam.ipynb
  examples/usecases/ecommerce-session-based-next-item-prediction-for-fashion.ipynb
  examples/usecases/entertainment-with-pretrained-embeddings.ipynb
  examples/usecases/incremental-training-with-layer-freezing.ipynb
  examples/usecases/multi-gpu-data-parallel-training.ipynb
  examples/usecases/ranking_with_multitask_learning.ipynb
  examples/usecases/transformers-next-item-prediction.ipynb
  merlin/models/tf/inputs/base.py
  merlin/models/tf/inputs/embedding.py
  merlin/models/tf/outputs/block.py
Labels: documentation

#1144 Remove `overwrite=True` argument from `df.to_parquet` in aliccp convert data
  merlin/datasets/ecommerce/aliccp/dataset.py
Labels: chore

#1145 Rename `prepare_alliccp` to `prepare_aliccp`
  merlin/datasets/ecommerce/__init__.py
  merlin/datasets/ecommerce/aliccp/dataset.py
  tests/unit/datasets/test_ecommerce.py
Labels: chore

#1126 Add Model class
  merlin/models/torch/__init__.py
  merlin/models/torch/block.py
  merlin/models/torch/models/__init__.py
  merlin/models/torch/models/base.py
  merlin/models/torch/utils/module_utils.py
  requirements/pytorch.txt
  tests/unit/torch/models/__init__.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/utils/test_module_utils.py
Labels: enhancement, area/pytorch

#1146 Run tests marked with `notebook` marker in examples workflow
  .github/workflows/gpu.yml
  Makefile
  examples/01-Getting-started.ipynb
  merlin/models/utils/ci_utils.py
  pytest.ini
Labels: ci, chore

#1102 add session-based example with pretrained embeddings
  examples/usecases/transformers-next-item-prediction-with-pretrained-embeddings.ipynb
  merlin/datasets/ecommerce/sigir/__init__.py
  merlin/datasets/ecommerce/sigir/browsing_train/__init__.py
  merlin/datasets/ecommerce/sigir/browsing_train/schema.json
  merlin/datasets/ecommerce/sigir/sku_information/__init__.py
  merlin/datasets/ecommerce/sigir/sku_information/schema.json
  merlin/datasets/synthetic.py
  tests/unit/tf/examples/test_usecase_transformers_next_item_prediction_with_pretrained_embeddings.py
Labels: examples

#1151 Run all tests when CI utils cannot detect changes
  tests/conftest.py
Labels: ci

#1152 Update the pretrained example notebook
  examples/usecases/transformers-next-item-prediction-with-pretrained-embeddings.ipynb
Labels: examples

#1149 Add schema tracing
  merlin/models/torch/__init__.py
  merlin/models/torch/batch.py
  merlin/models/torch/block.py
  merlin/models/torch/blocks/mlp.py
  merlin/models/torch/container.py
  merlin/models/torch/inputs/__init__.py
  merlin/models/torch/inputs/embedding.py
  merlin/models/torch/inputs/select.py
  merlin/models/torch/inputs/tabular.py
  merlin/models/torch/models/base.py
  merlin/models/torch/outputs/base.py
  merlin/models/torch/outputs/classification.py
  merlin/models/torch/outputs/regression.py
  merlin/models/torch/outputs/tabular.py
  merlin/models/torch/router.py
  merlin/models/torch/schema.py
  merlin/models/torch/transforms/agg.py
  merlin/models/torch/utils/module_utils.py
  merlin/models/torch/utils/schema_utils.py
  merlin/models/torch/utils/selection_utils.py
  merlin/models/torch/utils/torchscript_utils.py
  tests/unit/torch/_conftest.py
  tests/unit/torch/inputs/__init__.py
  tests/unit/torch/inputs/test_embedding.py
  tests/unit/torch/inputs/test_select.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/models/test_base.py
  tests/unit/torch/outputs/test_classification.py
  tests/unit/torch/outputs/test_regression.py
  tests/unit/torch/outputs/test_tabular.py
  tests/unit/torch/test_block.py
  tests/unit/torch/test_container.py
  tests/unit/torch/test_link.py
  tests/unit/torch/test_router.py
  tests/unit/torch/test_schema.py
  tests/unit/torch/transforms/test_agg.py
  tests/unit/torch/utils/test_module_utils.py
  tests/unit/torch/utils/test_schema_utils.py
Labels: enhancement, status/work-in-progress

#1153 Add importorskip for pytorch_lightning to torch tests
  tests/unit/torch/__init__.py
Labels: ci

#1112 Add Encoder & Predictor
  merlin/models/torch/predict.py
  tests/unit/torch/test_predict.py
Labels: enhancement, area/pytorch, status/needs-review

#1155 Update merlin dependency versions to match current release
  requirements/base.txt
Labels: ci, chore, skip-base-branch-check

#1154 Adding some extra methods to make working with blocks easier
  merlin/models/torch/block.py
  merlin/models/torch/models/base.py
  merlin/models/torch/router.py
  merlin/models/torch/schema.py
  merlin/models/torch/utils/module_utils.py
  merlin/models/torch/utils/traversal_utils.py
  tests/unit/torch/inputs/test_tabular.py
  tests/unit/torch/utils/test_module_utils.py
  tests/unit/torch/utils/test_traversal_utils.py
Labels: enhancement

#1163 We need to remove README after the hyper link.
  README.md
Labels: documentation
