Repository NVIDIA-Merlin/models, pull requests merged in 2024-01, with the labels that each got.

#1232 Fix sok import error in ut
  merlin/models/tf/distributed/backend.py
Labels: enhancement, 23.12

#1236 fix dependencies in docs build
  requirements/docs.txt
  tox.ini
Labels: documentation, ci, chore

#1235 move merlin dependecy install in horovod-cpu tests
  tox.ini
Labels: bug, ci, chore
